version: '2.0'

services:
  db:
    build: .
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080

volumes:
  db:
    driver: local