version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=example

volumes:
  db:
    driver: local
